version: '3.4'

services:
  eureka:
    image: openjdk:17-jdk-slim
    volumes:
      - '../discovery/build/libs/discovery.jar:/home/app.jar'
    command: [ 'java', '-jar', '/home/app.jar' ]
    ports:
      - '8761:8761'
  gps-api:
    image: openjdk:17-jdk-slim
    links:
      - eureka
    volumes:
      - '../gps-api/build/libs/gps-api.jar:/home/app.jar'
    command: [ 'java', '-jar', '/home/app.jar' ]
    ports:
      - '9010-9030:8080'
    environment:
      - SERVER_URI=http://eureka:8761/eureka
  rewards-api:
    image: openjdk:17-jdk-slim
    volumes:
      - '../rewards-api/build/libs/rewards-api.jar:/home/app.jar'
    command: [ 'java', '-jar', '/home/app.jar' ]
    ports:
      - '8030-8050:8080'
    environment:
      - SERVER_URI=http://eureka:8761/eureka
  trip-pricer-api:
    image: openjdk:17-jdk-slim
    volumes:
      - '../trip-pricer-api/build/libs/trip-pricer-api.jar:/home/app.jar'
    command: [ 'java', '-jar', '/home/app.jar' ]
    ports:
      - '8050-8070:8080'
    environment:
      - SERVER_URI=http://eureka:8761/eureka
  gateway:
    image: openjdk:17-jdk-slim
    volumes:
      - '../gateway/build/libs/gateway.jar:/home/app.jar'
    command: [ 'java', '-jar', '/home/app.jar' ]
    ports:
      - '8762:8762'
